version: "3"

services:

  nginx:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /run/user/$UID/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external: true
    name: nginx
